# PartyFactionsTop
# v1.0 (By ThreadSafety a.k.a evancolewright)
# Official File Configuration

# =====================================================================================================================
# DATABASE SETTINGS

# The database is NOT required, and is not used by the plugin internally.
# The purpose of the database is simply to dump values from each calculation into an
# online source for the purpose of displaying them on the web.
# This makes it possible to implement a "Top factions" interface into our website in the future.
# =====================================================================================================================
database:
  enabled: true
  host: "198.245.51.96"
  name: "db_224859"
  username: "db_224859"
  password: "eb550d4603"

# =====================================================================================================================
# FTOP SETTINGS
#
# These are the settings and timings for the FTop.
# These settings can make or break the performance of the server and the plugin itself.  It is recommended that
# you keep the current settings that are here by default as I have tested them EXTENSIVELY, and they work on even
# the LARGEST workloads (10,000+ chunk scans).  Nevertheless, feel free to test as much as you like.
# =====================================================================================================================
settings:
  recalculation_timeout: 60  # This is the duration between each ftop calculation in MINUTES.
  recalcuation_chunks_each_tick: 20  # During the calculation, this is how many chunks will be added to the queue for recalculation every 1/20 of a second. Default is 400 chunks per second.
  # include_player_balances: false  N/A

# =====================================================================================================================
# MESSAGES
#
# Yea, this section is pretty self-explanatory.
# =====================================================================================================================

messages:
  recalculation_starting:
    - ""
    - "&7&l(&b&l!&7&l) &bFactionsTop is now recalculating! You will be notified when this process completes."
    - "&b * &7Do &b/f top &7 to check the progress."
    - ""
  recalculation_completed:
    - ""
    - "&7&l(&b&l!&7&l) &bFactionsTop recalculation has completed!"
    - "&b * &7Took: &b{TIME}"
    - ""

  usage: "&cUsage: /f top <page>"
  calculating_ftop:
    - "&7&l(&b&l!&7&l) &bFactionsTop is currently recalculating!"
    - "&b * &7Progress&7: &b[{PROGRESS}&b] &7(&bCalculating all chunks&7)"
  compiling_ftop:
    - "&7&l(&b&l!&7&l) &bFactionsTop is currently recalculating!"
    - "&b * &7Progress&7: &b[{PROGRESS}&b] &7(&bCompiling all chunks&7)"

# =====================================================================================================================
# TOP LIST
#
# This is the message that you receive when performing /f top
# You may use the placeholders that are set in the worths section
# anywhere you wish inside here!!!
#
# Placeholders:
# {LEADER} - the leader of the faction
# {FACTION} - the faction
# {OVERALL_WORTH} - the overall worth of the faction
# {BLOCK_WORTH} - the overall worth of the faction
# {SPAWNER_WORTH} - the overall spawner worth of the faction
# {PAGE} - the current page of the f top
# {MAX_PAGE} - the max page of FTOP
# {PLACE} - the current position of the faction on ftop

# =====================================================================================================================
top_list:
  per_page: 10
  top_border:
    - "&b&l(!) &r&bFactions Top &7[&aPage {PAGE}/{MAX_PAGE}]"
  format: "&b&l* &a#{PLACE} &f{FACTION} &7 - {OVERALL_WORTH}"
  tooltip:
    - "&b&l(!) Faction Breakdown: {FACTION}"
    - "&b* &7Faction Leader&7: &b{LEADER}"
    - ""
    - "&b* &7Spawner Value: &b{SPAWNER_WORTH}"
    - "&b* &7Block Value: &b{BLOCK_WORTH}"
    - ""
    - "&b* &7Spawners:"
    - "&b - &7Cow: &b%cow%"
    - "&b - &7Zombie: &b%zombie%"
    - "&b - &7Skeleton: &b%skeleton%"
    - "&b - &7Blaze: &b%blaze%"
    - "&b - &7Zombie Pigman: &b%pig_zombie%"
    - "&b - &7Enderman: &b%enderman%"
    - "&b - &7Creeper: &b%creeper%"
    - "&b - &7Iron Golem &b%iron_golem%"
    - ""
    - "&b* &7Blocks:"
    - "&b - &7Hopper: &b%hopper%"
    - "&b - &7Becon: &b%beacon%"
    - "&b&l(!) &r&bClick to view spawners (Coming Soon)"
  bottom_border:
    - ""
    - "&b* &7Hover over a Faction for their &bValue Breakdown"
    - "&b* &7Currently Tracking: &b{AMOUNT} Factions &7[&7Every Hour&7]"
    - "&b* &7Last Update was &b{MINUTES} minutes&7 ago."


# The worths of each item.
# Again, the placeholder you set here can be used in the tooltip in the section above!!
worths:
  blocks:
    1:
      type: HOPPER
      worth: 5000
      placeholder: "%hopper%"
    2:
      type: BEACON
      worth: 10000
      placeholder: "%beacon%"
  spawners:
    1:
      type: COW
      worth: 10000
      placeholder: "%cow%"
    2:
      type: ZOMBIE
      worth: 25000
      placeholder: "%zombie%"
    3:
      type: SKELETON
      worth: 35000
      placeholder: "%skeleton%"
    4:
      type: BLAZE
      worth: 100000
      placeholder: "%blaze%"
    5:
      type: PIG_ZOMBIE
      worth: 125000
      placeholder: "%pig_zombie%"
    6:
      type: ENDERMAN
      worth: 200000
      placeholder: "%enderman%"
    7:
      type: CREEPER
      worth: 350000
      placeholder: "%creeper%"
    8:
      type: IRON_GOLEM
      worth: 1000000
      placeholder: "%iron_golem%"


