# RoyaleFTop
# v1.0 (By ThreadSafety a.k.a evancolewright)
# Official File Configuration

# Database settings
# Data is saved after each calculation.
database:
  enabled: true
  host: "198.245.51.96"
  name: "db_224859"
  username: "db_224859"
  password: "eb550d4603"


# Settings for the FTop Calculation process.
# The Overall Calculation process has 2 stages: Compilation and Calculation
# Compilation: The process of compiling all chunks on the server to a single list (Sync)
# Calculation: The process of evaluating each individual chunk for blocks of worth (Async)
# The compilation process can cause server lag, so a lower number is preferred.  With a lower number comes longer calculation times, however.
settings:
  recalculation_timeout: 60  # This is the duration between each ftop calculation in minutes.
  recalcuation_chunks_each_tick: 20  # During the calculation, this is how many chunks will be added to the queue for recalculation every 1/20 of a second.  This is done on asynchronously, so up to 50 is fine.
  compilation_chunks_each_tick: 10 # During the compilation process, this is how many chunks will get compiled every 1/20 of a second.  This process is completed on the main thread, so please be careful.

# Plugin messages
messages:
  recalculation_starting:
    - ""
    - "&7&l(&b&l!&7&l) &bFactionsTop is now recalculating! You will be notified when this process completes."
    - "&b * &7Do &b/f top &7 to check the progress."
    - ""
  recalculation_completed:
    - ""
    - "&7&l(&b&l!&7&l) &bFactionsTop recalculation has completed!"
    - "&b * &7Took: &b{TIME}"
    - ""
  usage: "&cUsage: /f top <page>"
  calculating_ftop:
    - "&7&l(&b&l!&7&l) &bFactionsTop is currently recalculating!"
    - "&b * &7Progress&7: &b[{PROGRESS}&b] &b[2/2] &7(&bCalculating all chunks&7)"
  compiling_ftop:
    - "&7&l(&b&l!&7&l) &bFactionsTop is currently recalculating!"
    - "&b * &7Progress&7: &b[{PROGRESS}&b] &b[1/2] &7(&bCompiling all chunks&7)"


# All chat settings.  Please place {FTOP_PLACE} in your chat format to use!
chat:
  format: "#"  # Will append this character(s) before the number placement in {FTOP_PLACE}
  no_faction: "-"  # Will append this
  default_color: "&f"  # The default color for the placements
  placements:
    1: "&c"
    2: "&b"
    3: "&7"
    4: "&6"
    5: "&9"

# The actual /ftop list formatting and tooltip.
#
# Placeholders
# {LEADER} - the leader of the faction
# {FACTION} - the faction
# {OVERALL_WORTH} - the overall worth of the faction
# {BLOCK_WORTH} - the overall worth of the faction
# {SPAWNER_WORTH} - the overall spawner worth of the faction
# {PAGE} - the current page of the f top
# {MAX_PAGE} - the max page of FTOP
# {PLACE} - the current position of the faction on ftop

top_list:
  per_page: 10
  top_border:
    - "&b&l(!) &r&bFactions Top &7[&aPage {PAGE}/{MAX_PAGE}]"
    - ""
  bottom_border:
    - ""
    - "&b* &7Hover over a Faction for their &bValue Breakdown"
    - "&b* &7Currently Tracking: &b{AMOUNT} Factions &7[&7Every Hour&7]"
    - "&b* &7Last Update was &b{MINUTES} minutes&7 ago."
  format: "&b&l* &a#{PLACE} &f{FACTION} &7 - {OVERALL_WORTH}"
  tooltip:
    - "&b&l(!) Faction Breakdown: {FACTION}"
    - "&b* &7Faction Leader&7: &b{LEADER}"
    - ""
    - "&b* &7Spawner Value: &b{SPAWNER_WORTH}"
    - "&b* &7Block Value: &b{BLOCK_WORTH}"
    - ""
    - "&b* &7Spawners:"
    - "&b - &7Cow: &b%cow%"
    - "&b - &7Zombie: &b%zombie%"
    - "&b - &7Skeleton: &b%skeleton%"
    - "&b - &7Blaze: &b%blaze%"
    - "&b - &7Zombie Pigman: &b%pig_zombie%"
    - "&b - &7Enderman: &b%enderman%"
    - "&b - &7Creeper: &b%creeper%"
    - "&b - &7Iron Golem &b%iron_golem%"
    - ""
    - "&b* &7Blocks:"
    - "&b - &7Hopper: &b%hopper%"
    - "&b - &7Beacon: &b%beacon%"
    - ""
  spawner_breakdown_text: "&b&l(!) &r&bClick to view spawners (Coming Soon)"

spawner_gui:
  name: "&b{FACTION}'s &7Spawner Breakdown"
  head_name: "&7(&b!&7) &b{SPAWNER} Spawners"
  head_lore:
    - "&b* &7Amount: &b{AMOUNT}"
    - "&b* &7Value per spawner: &b{VALUE}"
    - "&7Total Contribution to faction: &b&n{TOTAL}"



# The worths of each item.
# All placeholder you set here can be used in the tooltip above!
worths:
  blocks:
    1:
      type: HOPPER
      worth: 5000
      placeholder: "%hopper%"
    2:
      type: BEACON
      worth: 10000
      placeholder: "%beacon%"
  spawners:
    1:
      type: COW
      worth: 10000
      placeholder: "%cow%"
    2:
      type: ZOMBIE
      worth: 25000
      placeholder: "%zombie%"
    3:
      type: SKELETON
      worth: 35000
      placeholder: "%skeleton%"
    4:
      type: BLAZE
      worth: 100000
      placeholder: "%blaze%"
    5:
      type: PIG_ZOMBIE
      worth: 125000
      placeholder: "%pig_zombie%"
    6:
      type: ENDERMAN
      worth: 200000
      placeholder: "%enderman%"
    7:
      type: CREEPER
      worth: 350000
      placeholder: "%creeper%"
    8:
      type: IRON_GOLEM
      worth: 1000000
      placeholder: "%iron_golem%"


