name: RoyaleFTop
version: ${project.version}
main: io.github.evancolewright.royaleftop.RoyaleFTop
api-version: 1.8.8
authors: [ ThreadSafety ]
description: An asynchronously-focused and comprehensive worth calculator for FactionsUUID.
website: evancolewright.github.io
depend:
  - Factions
  - Vault
commands:
  factionstop:
    aliases: [ftop]
    description: View top factions
  ftopspawners:
    aliases:
      - factionstopspawners
    description: View spawner breakdown for a faction
  factionstopreload:
    aliases:
      - ftopreload
    description: Reload the config for the plugin
  factionstoprecalculate:
    aliases:
      - ftoprecalc
      - factionstoprecalc
    description: Force recalculate the ftop
  factionstoplock:
    aliases: [ftoplock]
    description: Locks the Ftop from updating further


